apiVersion: meta.dev.upbound.io/v1alpha1
kind: Project
metadata:
  name: silly-demo
spec:
  dependsOn:
  - provider: xpkg.upbound.io/upboundcare/provider-aws-ec2
    version: '>=v1.16.0'
  - provider: xpkg.upbound.io/upboundcare/provider-aws-rds
    version: '>=v1.16.0'
  - provider: xpkg.upbound.io/upbound/provider-azure-dbforpostgresql
    version: '>=v1.7.0'
  - provider: xpkg.upbound.io/upbound/provider-gcp-sql
    version: '>=v0.33.0'
  - provider: xpkg.upbound.io/crossplane-contrib/provider-sql
    version: '>=v0.9.0'
  - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
    version: '>=v0.15.0'
  - function: xpkg.upbound.io/crossplane-contrib/function-status-transformer
    version: v0.4.0
  - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
    version: '>=v0.0.0'
  description: This is where you can describe your project.
  license: Apache-2.0
  maintainer: Ivan Rizzante <i.rizzante@gmail.com>
  readme: |
    This is where you can add a readme for your project.
  repository: xpkg.upbound.io/irizzant/silly-demo
  source: https://github.com/vfarcic/upbound-devex-demo
