apiVersion: devopstoolkit.live/v1alpha1
kind: SQL
metadata:
  name: my-db
  namespace: default
spec:
  id: my-db
  compositionSelector:
    matchLabels:
      provider: aws
      db: postgresql
  parameters:
    version: "16.2"
    size: medium
    region: us-east-1
